Created artifactory script
prismskylabs/connect pull request #27
Opened 2017-02-18 00:42 UTC by andrii-prism

2017-02-18 01:34 UTC, Yurmusp commented on CMakeLists.txt
> +    add_custom_target(artifactory
I would call it upload_delivery or artifactory_delivery instead of artifactory.

2017-02-21 20:24 UTC, dbus-prsm requested changes

2017-02-21 20:24 UTC, dbus-prsm commented on build.sh
> +        --upload-delivery)
Add new argument description into the script header.

2017-02-21 20:24 UTC, dbus-prsm commented on CMakeLists.txt
> +        jfrog rt u ${PROJECT_SOURCE_DIR}/${PROJECT_NAME}_${SDK_VER}_${REV_HASH}_${PRISM_PLATFORM}.${CONNECT_BUILD_TYPE}.tar.gz libs-release-local/${PRISM_PLATFORM}/
You should use a variable to store the archive file name to avoid a discrepancy in naming for delivery targets.

2017-02-21 23:24 UTC, andrii-prism commented on build.sh
> +        --upload-delivery)
done

2017-02-22 19:24 UTC, dbus-prsm approved these changes

2017-02-22 23:01 UTC, Yurmusp commented on CMakeLists.txt
> +    add_custom_target(upload_artifactory
either upload_artifact or upload_to_artifactory

2017-02-23 00:20 UTC, merged